name: Build and Commit LaTeX PDF

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: LineFollowingRobot_Report

      - name: Rename PDF
        run: |
          mv LineFollowingRobot_Report/main.pdf LineFollowingRobot_Report/report.pdf

      - name: Pull latest changes
        run: |
          git pull --rebase origin main

      - name: Commit PDF to Repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update generated PDF
          file_pattern: LineFollowingRobot_Report/report.pdf
